# USAGE:
# * Set LLVM version desired:
#   $ export LLVM_TARGET_VER
#   $ LLVM_TARGET_VER=4.0
#
# * Build:
#   $ docker-compose build
#
# * Run:
#   $ docker-compose run crystal_lang
#     * then check the version info w/in the docker console, e.g.:
#
#       ```
#       root@4da50da8e066:/opt/crystal-head# echo $LLVM_TARGET_VER
#       4.0
#
#       root@4da50da8e066:/opt/crystal-head# .build/crystal -v
#       Crystal HEAD (2017-09-21)
#
#       LLVM: 4.0.0
#       Default target: x86_64-pc-linux-gnu
#       ```
#
version: '3'
services:
  crystal_lang:
    build:
      context: .
      args:
        - LLVM_TARGET_VER
    environment:
      LLVM_TARGET_VER: ${LLVM_TARGET_VER}
